### ISSUE TITLE
Reduce size of images. 

### ISSUE THREAD

**Issue by kqdreger** [kqdreger/thelivingwell.co#6]
The max width of our content column is ~ 600px. Ideally, we'd have images be web-optimized and around 1200px wide. Current homepage size is 9.5MB, which can kill on mobile connections.

**Comment by sarahkay3** [comment]
I reduced about 16 assets. Let me know if you think that made enough of a dent? I'll set my ratio's for that perspective and change them all in photoshop before uploading from here on out.

**Comment by kqdreger** [comment]
Nice! You reduced page weight by about half 👍
